### ISSUE TITLE
Support for `SdFat` has been removed?

### ISSUE THREAD

**Issue by SmittyHalibut** [WMXZ-EU/MTP_t4#17]
The original library this was based on (https://github.com/yoonghm/MTP) was written to use `SdFat`.

Your comments here: https://github.com/WMXZ-EU/MTP_t4/blob/master/src/Storage.h#L24-L26 are unclear on your intent with regards to library support.

But the CURRENT revision looks like it has REMOVED `SdFat` support.  Is this intentional?  Is the use of `SdFat` discouraged now?  I thought it was the preferred library to access files on an SD card on a Teensy; am I wrong?  (I'm not an expert on this, I'm still figuring out the whole SD Card On Teensy space.)

**Comment by WMXZ-EU** [comment]
SdFat (V2) is now the basic library behind SD.h and is installed automatically with Teesnsyduino.
Private SdFat-beta, SdFat-V2 should be removed
