### ISSUE TITLE
Teensy 4.1 not showing as MTP storage device

### ISSUE THREAD

**Issue by asinghnu** [WMXZ-EU/MTP_t4#21]
Teensy 4.1  is used as data logger ,however after doing the changes in files as mentioned in MTP_t4 there is no Teensy as storage device
although the data is updated in sdcard (32 GB). the same changes done in other computer shows it as storage but when i upload program from my computer it fails as storage .system specifications are Teensy 4.1,windows 10,Teensyduino, Version 1.5,arduino-1.8.19

**Comment by WMXZ-EU** [comment]
Does MTP device show up with mtp_basic?
using MTP during and after logging is very tricky, as MTP is designed mainly for file transfers that exist when MTP is initiated.

**Comment by asinghnu** [comment]
my port on Arduino shows as "COM 20 Serial Teensy ",not sure whether it shows up with MTP_basic,device manager detects as USB .can you please guide with all modifications required

**Comment by WMXZ-EU** [comment]
You must set USB type to MTP disk (either serial or not)
Port will shoe up as Everything

**Comment by asinghnu** [comment]
port is showing as "hid#vid_16c0&pid_04d1 MTPDisk(Teensy4.1) when selected usb as mtp disk.still the no storage device present

**Comment by WMXZ-EU** [comment]
Just compiled mtp-basic for T3.6 and T4.1 and no issue
(added "include <SPI.h>" at top of file, see actual github file)
