### ISSUE TITLE
Can MTP access be "started" and "stopped" from the teensy?

### ISSUE THREAD

**Issue by cfeied** [WMXZ-EU/MTP_t4#3]
Desired scenario: My teensy code runs in different modes. When first connected, the mode is set to mtpMode and the SD card should be accessible from the PC. When the device is switched into a different program mode, the USB drive should no longer be accessible from the PC.

I attempted to do this by calling mtpd.loop() only when mode == mtpMode.  Unfortunately, when I switch to another mode this causes Windows Explorer/ ThisPC (and other things) to hang forever. Presumably Explorer is blocked waiting for a response from mtpd. 

Is there a way to accomplish this?  Switching off the teensy causes Windows Explorer to close, which is the ideal desired behavior, but seems to be tied to USB teardown. I'd be satisfied with showing a drive that reported "access denied," or something else along those lines.

**Comment by WMXZ-EU** [comment]
When mtpd.loop() is not called there is no communication between Teensy and PC.
consequently Windows explorer is "frozen". As soon you call mtpd.loop() again communication continues.
As mtpd.loop is processing exclusively (not running asynchronously), this should be save. 
Never had the effect you describe and I'm using the method that is also shown in mtp_logger.ino extensively.
Obviously, PC does not rescan directories that it already scanned, so new files in that directory are not visible.
I will keep an eye on this effect
