### ISSUE TITLE
Desire to use MTP on the USB1 (USBHS) port on t3.6, 4.0, and 4.1

### ISSUE THREAD

**Issue by cfeied** [WMXZ-EU/MTP_t4#5]
I have seen comments indicating that in some earlier version of the MTP it was possible to connect via a high-speed port rather than the 12 Mbps main port. There was some reference to an example, but I have not been able to find such an example. This would be highly desirable functionality.

**Comment by WMXZ-EU** [comment]
USBHS device mode was done for T3.6.
May test and publish MTP port to T3.6 USBHS.
