### ISSUE TITLE
Warning Wmisleading-indentation

### ISSUE THREAD

**Issue by FrankBoesing** [WMXZ-EU/MTP_t4#6]
`C:\Users\Frank\Documents\Arduino\libraries\MTP_t4-master\src\MTP.cpp:875:9: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
  875 |         if(!write_length_) dst=tx_data_buffer;   write_length_ += len;
      |         ^~
C:\Users\Frank\Documents\Arduino\libraries\MTP_t4-master\src\MTP.cpp:875:50: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'
  875 |         if(!write_length_) dst=tx_data_buffer;   write_length_ += len;
      |                                                  ^~~~~~~~~~~~~
Compiling library "USB2-master"
`

**Comment by WMXZ-EU** [comment]
statement is correct, but I reformatted code
